### ISSUE TITLE
prompt does not always show up when it should

### ISSUE THREAD

**Issue by stefanofornari** [stefanofornari/BshConsole#10]
This happens probably when the command takes a while to process, so when we ask for the prompt a wrong value is available. I need to find a more reliable way...

**Comment by nickl-** [comment]
Not sure I follow? What gets displayed? Do you have example output? steps to reproduce perhaps?

**Comment by stefanofornari** [comment]
I still need to find reliable way to reproduce it...

Ste

**Comment by stefanofornari** [comment]
It is now fixed. closing,

**Comment by nickl-** [comment]
It still works for me too with and I haven't pulled anything yet.

**Comment by stefanofornari** [comment]
now it systematically works for me too :)

Ste
