### ISSUE TITLE
tab-completion improvements

### ISSUE THREAD

**Issue by stefanofornari** [stefanofornari/BshConsole#12]
We want to improve tab completion based on @nickl- proposal in https://github.com/stefanofornari/BshConsole/pull/3.

**Comment by stefanofornari** [comment]
hey @nickl-, back on a piece of the code you proposed in BshCompleter:
static {
       BshClassPath.addMappingFeedback(new ClassPathMappingFeedback());
}

I understand this is required to mute the output the default ClassPathMappingFeedback produces. However I see it is a static call, therefore this applies globally. 
Should we:

1. put it outside BshCompleter instead
2. replicate the functionality (essentially ((ClassManagerImpl) bsh.getNameSpace().getClassManager()).getClassPath())
3. modify the default ClassPathMappingFeedback to a muted one?

I will go for 1 for now, but I am ok to change it later.

**Comment by stefanofornari** [comment]
https://github.com/stefanofornari/BshConsole/commit/1d60c3f642d4c9829b6c0267934450af90d47ce1

**Comment by nickl-** [comment]
Initially I thought it might get useful information for completion but it only serves to shut it up really. That class takes 2 more listeners...someone really loved them listeners. 

As for 3. it doesn't use a default.. hence the need to add one =( 
If it doesn't find the mapping feedback it hollers at `System.err.println` with all that noise.

It is static yes, and there is no way to remove it once added... but at least it serves the purpose of muting the output. I agree it doesn't have to be in the completer per se, any class that will get statically initialized will do. .

No 2. Seems like reinventing the wheel... lets rather see if we can't get that crooked wheel `NameCompletion` which we already have... more wheel like instead. =) It already does some of what we want at least.

Agree?

**Comment by stefanofornari** [comment]
I agree. Let's go for 2.



Ste

**Comment by nickl-** [comment]
> I agree. Let's go for 2.

Do you mean 1 not 2... 2 is reinventing the wheel I agreed with your 1st assessment to go with option 1 add the Mapping feedback as an external statically referenced solution.

**Comment by stefanofornari** [comment]
implemented.
