### ISSUE TITLE
^C Cannot interrupt loops

### ISSUE THREAD

**Issue by nickl-** [stefanofornari/BshConsole#13]
The new modification does not recover from loop interruption and also doesn't stop the loop leaving orphan thread running.

To reproduce

```
bsh % a = 1;
bsh % while (true) a++;

(...)





```

**Comment by stefanofornari** [comment]
ah, indeed. now I see your point! I was targeting just discarding the
parsed content, I did not originally want to interrupt execution.
But I am not sure the other approach will make the trick neither. if a node
is busy into a while(true) loop the REPL condition will not get checked
anyway. Right?


Ste

**Comment by stefanofornari** [comment]
@nickl- , can you please point me on the right path about how you achieved this in pr#4? is the Thread.interrupt() in the caller and then the implementation of all loops in beanshell check the status of the thread?

a pointer to the code would be enough.

thanks in advance

**Comment by stefanofornari** [comment]
I think I found it, it is in code like

```
while ( !Thread.interrupted()
                && ( doOnceFlag || BSHIfStatement.evaluateCondition(condExp, callstack, interpreter)) ) {
```

which is indeed a good practice. however, I am still not digesting that we need to interrupt the main thread where the REPL is running. it is overkilled.

Would you be ok to use the interrupted field (introduced in pull #86) instead? If instead we want to use Thread.interrupt we should probably execute the code in a separate thread: one thread for the parser, one thread to execute the code. It would actually open to many interesting things, like executing some commands asynchronously...

**Comment by nickl-** [comment]
Yes the !Thread.interrupted is just to make the loops abort quicker. They would abort on their own eventually with the interpreter reset.

Restarting interpreter is not as expensive as you think, infant you are already launching and closing several interpreters in the console, before you even started the thread. 

Have a closer look at the `eval` method and `enclosingInterpreter` it creates a new interpreter just for eval which is closed again via try-with-resource. This is the way we to do it and not bother with the parser which should be protected from modification by interpreter.

**Comment by nickl-** [comment]
Here is the debug stats, I had to change it from milliseconds to nanoseconds because it reported the time taken, simply as 0. As you can see it is still very close to zero in any case.

1st init with null namespace: now with the singleton as static this starts long before we actually need it.

**Time to initialize interpreter: 34824463 nanoseconds = 0,034824463 seconds**

Re-initialize with interpreter as parent:

**Time to initialize interpreter: 11338 nanoseconds = a flash**

As you can see it is really inconsequential.

**Comment by stefanofornari** [comment]
closing with https://github.com/stefanofornari/BshConsole/commit/22715379119e6a30ddb2bb35376b2ec583c8a851

**Comment by nickl-** [comment]
So instead of interrupting the interpreter thread we now evaluate everything in a separate thread so that we can interrupt it.

hmmmmm...

**Comment by stefanofornari** [comment]
If with "evaluate" you mean the actual execution of the nodes, yes exactly. currently in the REPL we do two things:

1. parse the input with Line
2. and subsequently run the nodes

these two are not necessarily a sequence, and we may actually think of spawning the execution even in a asynchronous  thread so that you could go on with other statements. It would indeed not make sense to stop the parsing task killing the interpreter thread if you just want to stop the execution.

This seems a cleaner approach to me. I am not quite clear instead what the advantages of shutting down the entire interpreter and starting it again are...

**Comment by nickl-** [comment]
> This seems a cleaner approach to me. I am not quite clear instead what the advantages of shutting down the entire interpreter and starting it again are...

It is just how he interpreter was designed. While you are holding onto this single instance of the interpreter you fail to notice that on every `getBshPrompt()` call we started a new interpreter and let it die. Every time...

The parsing and evaluating are not two separate things, and there is no benefit in forcing them to be separate. The state is kept in the namespace, that is all we need. We can even serialize it and fire it up again on a completely different machine and your whole session is restored. This is all we need and the only reason that we need to pass interpreter as the parent, it is not because of the interpreter or the parser or any input partial or completed. We add the interpreter as parent only because it supplies the namespace of the previous session.

Retain the namespace and we can start interpreting new input anywhere anytime anyhow. Why do you insist on keeping that interpreter instance? The only thing we need from it is the namespace nothing else is of any use.

I was really excited to include BshConsole  in the upcoming release, we started off at a productive pace and we could've had syntax highlighting done already not to mention completion. Instead we are still debating the same damn issue more than a month later and zero progress. Instead of using interpreter as it is implemented you would rather waste days to reimplement, redevelop, redesign, while there is already a working implementation.

There is so much that remains outstanding which doesn't work. Existing code that is not covered with unit tests so we can't know for sure if it does work or not. This procedure works it is thoroughly covered and reused in several scenarios from console to servlets to script engine and applets.... I really really really don't understand why we need to waste time to develop an alternative approach. While there are literally tons of work we should rather be doing.

I am really dissapointed with the progress to say the least... if instead you focused on developing the console there would be something to bring to the table already. You do not need to change BeanShell or jline for that matter what we need is working functionality to get implemented on BshConsole. How it gets done matters very little the only thing that is important is getting it done.

You should ask yourself what it is that you want to accomplish here? If your plan is to add a stupidly fantastic and awesome console to BeanShell then count me in I'll help with anything or do you want to rewrite BeanShell for your console. I can't do both...
