### ISSUE TITLE
Interpreter changes take note

### ISSUE THREAD

**Issue by nickl-** [stefanofornari/BshConsole#19]
Heads up: beanshell/beanshell@014e83b made some changes to Interpreter, see if it affects you.

**Comment by stefanofornari** [comment]
Thanks! noted.

**Comment by stefanofornari** [comment]
The changes do not affect bshconsole, but I wonder if the following is wanted:

```
BEFORE
bsh % bsh.prompt="hello>";
hello>

NOW
bsh % bsh.prompt="hello";
bsh %
```

Closing.

**Comment by nickl-** [comment]
@stefanofornari  Tx for this!
