### ISSUE TITLE
completion adds an extra space once an exact match is found 

### ISSUE THREAD

**Issue by stefanofornari** [stefanofornari/BshConsole#4]
As reported by @nickl- when an exact match is found, an additional space is added to the completed text. This is undesirable in BeanShell.

**Comment by stefanofornari** [comment]
I found how to fix it. However this requires a change to jline. I am going to submit a PR, let's see if they accept it...

**Comment by stefanofornari** [comment]
https://github.com/jline/jline3/pull/287

**Comment by stefanofornari** [comment]
closed with complete=false, no need to the PR.

**Comment by nickl-** [comment]
Damn...some documentation would've been grand.

**Comment by stefanofornari** [comment]
fixed on trunk. i am reopening it, I will close it on new release.

**Comment by stefanofornari** [comment]
available in v1.2.0
